# Authentication
auth = "plain[passwd=/etc/ocserv/config/ocpasswd]"

# TCP and UDP port number
tcp-port = 443
udp-port = 443

# Socket file
socket-file = /var/run/ocserv-socket

# The key and the certificates of the server
server-cert = /etc/ocserv/certs/server-cert.pem
server-key = /etc/ocserv/certs/server-key.pem

# Worker isolation
# Must be false in Docker containers to avoid seccomp syscall clashes with the host
isolate-workers = false

# Maximum number of clients
max-clients = 16
max-same-clients = 2

# Rate limiting
rate-limit-ms = 100

# Keepalive and Dead Peer Detection
keepalive = 32400
dpd = 90
mobile-dpd = 1800

# MTU Discovery
try-mtu-discovery = false
mtu = 1280

# Authentication timeout
auth-timeout = 240
cookie-timeout = 300

# Banning clients
max-ban-score = 80
ban-time = 300
ban-reset-time = 1200

# Security (TLS Priorities)
tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT"

# Client Compatibility
cisco-client-compat = true

# The name to use for the tun device
device = vpns

# Predictable IPs
predictable-ips = true

# IPv4 subnet for VPN clients
ipv4-network = 192.168.211.0
ipv4-netmask = 255.255.255.0

# DNS settings
tunnel-all-dns = true
dns = 8.8.8.8
dns = 1.1.1.1

# Routing
# 'default' routes all traffic through the VPN (Full Tunnel)
route = default
